### ISSUE TITLE
Priority Rank Promote/Demote is not reflected in a database change?

### ISSUE THREAD

**Issue by Kaleidics** [code4sac/neighborhood-connect#56] opened 2019-07-26 04:29 UTC
From what I see on PrioritiesOrderPage.js we are able to promote/demote priorities. But this only reflects the local state of our app. It doesn't actually change anything in the database. Any idea, if the endpoint on the API exists for this?

**Comment by ryanmdoyle** [comment] 2019-07-26 06:13
It supposedly exists, I tried it on Monday but it wasn’t working. With the clearest merge to the api dev branch it should work. I was planning to try those out tomorrow.

**Comment by ryanmdoyle** [comment] 2019-07-26 07:16
This is a duplicate of issue #29

**Closed by ryanmdoyle** 2019-07-26 07:16 UTC
